### PR TITLE
Fixes for frontend Interface

### LINKED ISSUE #4: Interactable UI elements should be visually recognizable
Saw a quick demo of the new RefBox interface on the Carologistics meeting today, looks very promising!

A few usability issues were noted. One of them is the fact that active GUI elements should be recognizable as such. So in every GUI you have to have some conventionalized distinction between clickable/interactable stuff and non-interactable elements. Traditionally, it's this 3D shading effect you often see on buttons, a shaded inset frame on editable boxes, etc.

Doesn't even matter that much how you make the distinction, it could also be color, a hover effect (less preferred because it's not immediately visible) or a different drawing style. But some kind of distinction has to be there, because without it the UI becomes quite unapproachable.

It's important to recognize that this UI will be used by people possibly under significant cognitive, sensory and emotional stress.

### LINKED ISSUE #5: Dark background should be dark
The background color we saw in the demo today was too bright for a dark background. So generally, if you have a dark background with bright text, the background should actually be very dark, i.e. much closer to `#000`. Otherwise you end up with too many colors you can't use for informative elements because the contrast is too low. Also remember that the UI may have to be used in difficult viewing conditions, e.g. on a bad screen with sunlight shining on it, further worsening the contrast ratio.

### PR DESCRIPTION
**Pull request by userin4o**
This PR fixes #4, #5 

### It adds following:

- All  active GUI elements  are visually recognizable on hover.
-  The background is now dark and the contrast correspondingly adjusted.
- Attention messages are also being logged.
- Orders, whose delivery time is active are being displayed active, whereas inactive orders are being grayed out. 
- Box-shadow of the button (Add Team - ) changed to the color of the corresponding team.

### CODE REVIEW

File: frontend-client/src/components/BodyRefboxLog.vue [hunk 1]
```diff
@@ -1,20 +1,92 @@
...
+      <button @click=connect class="btn btn-primary "> Connect </button>
+      <button @click=disconnect class="btn btn-primary  ">
+        DC
+      </button>
+      <button @click=send class="btn btn-primary ">Send Msg</button>
+    </div>
+    
+    <div class="mx-3 mt-3">
+      <div v-for="(msg,index) in msgArray" :key=index>
+          <h6 v-if="msg.level !== 'attention' " class= "mb-0" :class="setClassName(msg.level)">{{msg.time}} [{{msg.component}}]: {{msg.message}}</h6>
```
Comment (snoato) [inline frontend-client/src/components/BodyRefboxLog.vue:13]: I would suggest using the same font size for these messages and attention messages and to use a monospaced font

File: frontend-client/src/components/HeaderTeam.vue [hunk 2]
```diff
@@ -123,7 +123,7 @@ export default {
 }
 
 .btn-magenta-header:hover {
-  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19) !important;
+  box-shadow: 0 12px 16px 0 var(--main-magenta-color) ,0 17px 50px 0 rgba(0,0,0,0.80) !important;
```
Comment (snoato) [inline frontend-client/src/components/HeaderTeam.vue]: I think the offset can be reduced, because it "shines" into the the text field below and the transition could be a bit faster to make it feel snappier

**Review by snoato — COMMENTED** [review]
Looks good overall! The changes make it easier to read. I added some suggestions, please let me know what you think!

File: frontend-client/src/components/BodyRefboxLog.vue (hunk 1 above)
Comment (userin4o) [reply frontend-client/src/components/BodyRefboxLog.vue:13]: Thanks for the suggestion. I did make all the logged messages the same size. As for the font, it is already a monospaced font (Helvetica)

File: frontend-client/src/components/HeaderTeam.vue (hunk 2 above)
Comment (userin4o) [reply frontend-client/src/components/HeaderTeam.vue]: Thanks, it is way snappier with the reduced transition time and I also reduced the vertical offset so it doesn't overflow.

**Comment by userin4o** [comment]
Dani, I pushed the changes, could you let me know, if the they are as desired

File: frontend-client/src/components/BodyRefboxLog.vue (hunk 1 above)
Comment (snoato) [reply frontend-client/src/components/BodyRefboxLog.vue:13]: Thank you! I think the same size makes it look more unified and doesn't break the flow as much.

Helvetica is not a monospaced font but a sans-serif, variable-width font. It is also not available on all devices (especially Linux distributions, because Helvetica licenses are not free, these usually default to a generic sans-serif font). Monospaced fonts include Menlo, Courier New, Roboto Mono, Source Code Pro, etc.

File: frontend-client/src/components/HeaderTeam.vue (hunk 2 above)
Comment (snoato) [reply frontend-client/src/components/HeaderTeam.vue]: For me it does still overflow, the new transition time looks great though! Bildschirmfoto 2020-05-30 um 12 20 19

**Review by snoato — APPROVED** [review]
Looks good now! Thank you! Feel free to merge, no objections from my side!

**Comment by userin4o** [comment]
Thanks!
